# Form implementation generated from reading ui file 'organizador_arquivos.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(603, 667)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.txt_titulo = QtWidgets.QLabel(self.frame)
        self.txt_titulo.setObjectName("txt_titulo")
        self.verticalLayout.addWidget(self.txt_titulo)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.le_caminho = QtWidgets.QLineEdit(self.frame)
        self.le_caminho.setMinimumSize(QtCore.QSize(0, 28))
        font = QtGui.QFont()
        font.setItalic(True)
        self.le_caminho.setFont(font)
        self.le_caminho.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.le_caminho.setObjectName("le_caminho")
        self.horizontalLayout_2.addWidget(self.le_caminho)
        self.btn_sele_pasta = QtWidgets.QPushButton(self.frame)
        self.btn_sele_pasta.setMinimumSize(QtCore.QSize(120, 28))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_sele_pasta.setFont(font)
        self.btn_sele_pasta.setStyleSheet("QPushButton{border-top-right-radius:15px; background-color:rgb(234,234,234)}\n"
"QPushButton:hover{color:#fff; background-color: rgb(0,157,235)}")
        self.btn_sele_pasta.setObjectName("btn_sele_pasta")
        self.horizontalLayout_2.addWidget(self.btn_sele_pasta)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.btn_renomear = QtWidgets.QPushButton(self.frame)
        self.btn_renomear.setMinimumSize(QtCore.QSize(200, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_renomear.setFont(font)
        self.btn_renomear.setStyleSheet("QPushButton{border-radius:15px; background-color:rgb(234,234,234)}\n"
"QPushButton:hover{color:#fff; background-color: rgb(0,157,235)}")
        self.btn_renomear.setObjectName("btn_renomear")
        self.horizontalLayout.addWidget(self.btn_renomear)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.txt_titulo.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#0000ff;\">Renomeador de Arquivos</span></p></body></html>"))
        self.le_caminho.setPlaceholderText(_translate("MainWindow", "Selecione uma pasta"))
        self.btn_sele_pasta.setText(_translate("MainWindow", "Pasta..."))
        self.btn_renomear.setText(_translate("MainWindow", "Renomear"))
